### ISSUE TITLE
Dropbox upload - filename contains illegal characters on Windows filesystems

### ISSUE THREAD

**Issue by eddie-planetnet** [jitsi/jitsi-upload-integrations#13]
This might be the wrong repo to raise this issue, if so I can bring it over to Jibri. Filenames that Jibri produces contain colon (":") characters in the timestamp. When uploading to Dropbox via the integration, that character is not stripped. As such the Dropbox Windows client does not sync those recordings. 

For me, as a quick fix, I modified the function in jitsi_uploader.sh which passes the file to the Dropbox uploader.

`function dropbox_upload {
    echo "Upload method: dropbox"
    UPLOAD_BIN="$BIN_PATH/dropbox_uploader.sh"
    export OAUTH_ACCESS_TOKEN=$TOKEN
    $UPLOAD_BIN -b upload "$1" "${2//:}"
    return $?
}`

**Comment by aaronkvanmeerten** [comment]
This is also an issue referenced in the jibri repo, so linking that one here: https://github.com/jitsi/jibri/issues/294

**Comment by aaronkvanmeerten** [comment]
The issue is with the date command used to build the filename.
`            MTIME=$(stat -c %Y "$i")
            FDATE=$(date --date="@$MTIME" '+%F %R')
`

**Comment by aaronkvanmeerten** [comment]
This PR is intended to resolve this issue: https://github.com/jitsi/jitsi-upload-integrations/pull/14

**Comment by aaronkvanmeerten** [comment]
This is now fixed and published in the latest debian package: jitsi-upload-integrations_0.14.14-1_all.deb
